### PR TITLE
Ampdev adil

### PR DESCRIPTION
**Pull request by adilfaiz001**
@zrthxn 
Request to review this User account coupon commit.

### CODE REVIEW

**Comment by zrthxn** [comment]
You haven't made the build (production) version.
In the **account** folder, run the following line from the terminal
```
npm run build
```

Then delete the Source Map file by going to
**account > build > static > js**
and delete the file with .map extension

Repeat the same thing with the merchant folder and then push to your branch. After that I can review the changes.

**Comment by zrthxn** [comment]
If you get errors then you might have done something wrong

**Comment by adilfaiz001** [comment]
But I haven't install node modules locally, so how to run npm run build command in account,
In [amphere-test.tk](http://amphere-test.tk), I made changes locally and push changes to server and run command `,npm run-script build`  on server to build production model.

**Comment by zrthxn** [comment]
Then install the node modules locally. Just run npm install for that.

After installing, run the build command.

**Comment by adilfaiz001** [comment]
I commit production build as you told.
This is account production build, as I didn't made any changes in merchant.

**Comment by adilfaiz001** [comment]
@zrthxn

**Pull request merged**
